defmodule Xo.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :email, :citext, null: false
      add :name, :text, null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:moves, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :field, :bigint, null: false
      add :move_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :player_id,
          references(:users,
            column: :id,
            name: "moves_player_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :game_id, :bigint, null: false
    end

    create table(:games, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:moves) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "moves_game_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create unique_index(:moves, [:game_id, :field], name: "moves_unique_field_per_game_index")

    create unique_index(:moves, [:game_id, :move_number],
             name: "moves_unique_move_number_per_game_index"
           )

    alter table(:games) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :player_o_id,
          references(:users,
            column: :id,
            name: "games_player_o_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :player_x_id,
          references(:users,
            column: :id,
            name: "games_player_x_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:games, "games_player_o_id_fkey")

    drop constraint(:games, "games_player_x_id_fkey")

    alter table(:games) do
      remove :player_x_id
      remove :player_o_id
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:moves, [:game_id, :move_number],
                     name: "moves_unique_move_number_per_game_index"
                   )

    drop_if_exists unique_index(:moves, [:game_id, :field],
                     name: "moves_unique_field_per_game_index"
                   )

    drop constraint(:moves, "moves_game_id_fkey")

    alter table(:moves) do
      modify :game_id, :bigint
    end

    drop table(:games)

    drop constraint(:moves, "moves_player_id_fkey")

    drop table(:moves)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
