defmodule Xo.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:games, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :player_o_id,
          references(:users,
            column: :id,
            name: "games_player_o_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :player_x_id,
          references(:users,
            column: :id,
            name: "games_player_x_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :winner_id,
          references(:users,
            column: :id,
            name: "games_winner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :state, :text, null: false, default: "open"
    end
  end

  def down do
    drop constraint(:games, "games_player_o_id_fkey")

    drop constraint(:games, "games_player_x_id_fkey")

    drop constraint(:games, "games_winner_id_fkey")

    drop table(:games)
  end
end
