defmodule Xo.Repo.Migrations.AddMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "messages_user_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :game_id,
          references(:games,
            column: :id,
            name: "messages_game_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:messages, "messages_user_id_fkey")

    drop constraint(:messages, "messages_game_id_fkey")

    drop table(:messages)
  end
end
